### PR TITLE
New plugin creater

### PR DESCRIPTION
**Pull request by mohrekopp**
This PR changes the default behavior of the plugin-generator. 
Now the generator will create a plugin-boilerplate for the new plugin-system introduced in Shopware 5.2. 
Legacy-plugins can also be created with a newly added command-line option.

- added **--legacy**-Option to command **plugin:create**
- added LegacyDefaultFileProvider. The DefaultFileProvider now returns only templates for new plugins
- the generated phpunit.xml.dist will use _tests/Functional/bootstrap.php_ for bootstrapping.
- a blank _services.xml_ will be created. If a console-command is created, it will be automatically added to _services.xml_

### CODE REVIEW

**Comment by dnoegel** [comment]
Hi,

great change, thanks. Only thing that should be corrected: Subscribers are still registered the "old" way. The recommended way now is to do that using the shopware.event_subscriber tag:

```
        <service id="lorem_questions.controller" class="LoremQuestions\Subscriber\Controller">
            <argument type="service" id="service_container" />
            <tag name="shopware.event_subscriber" />
        </service>
```

If that was merged, we could merge it right away, I think

**Comment by FiveDigital** [comment]
btw. this is missing in the documentation (https://developers.shopware.com/developers-guide/plugin-system/) ^^

**Comment by mohrekopp** [comment]
@dnoegel Thanks for the feedback. Do we need the onStartDispatch-Callback yet?

**Comment by mohrekopp** [comment]
@FiveDigital There is already a PR for the docs: https://github.com/shopware/devdocs/pull/316/commits/cdf216b04ca1db5d982d9ad951e0793df6b052ea

**Comment by dnoegel** [comment]
@mohrekopp No, generally I'd say, you don't need that event / callback anymore in the new system

**Comment by mohrekopp** [comment]
Ok, now after deleting the callback I wonder how to autoload API-Resources, which have to be hold under **Shopware\Components\Api** namespace :-/

**Comment by dnoegel** [comment]
Yes, you are right - if you need to have custom namespaces, you will still need some sort of "early" event - I just meant you won't need those events for event registration anymore. 
Technically you could also put the API components in a custom namespace - but then the API resource manager / factory cannot be used anymore, so it is probably a good practice to use the Shopware\Components\Api namespace

**Comment by mohrekopp** [comment]
Ok, now the callback will be added, if the plugin-generator is used with **--haveApi** option.

**Comment by FiveDigital** [comment]
@dnoegel We are currently implementing a PR to load the API resources through the DI container, too: https://github.com/shopware/shopware/pull/688

**Comment by SimonBaeumer** [comment]
Hi @mohrekopp ,

I tested you're PR and it looks very nice. I work on top of it, due to undocumented best practices, i.e. moving the `Snippets` directory to `Resources\snippets` and some little namespace issues.

Thank you in advance!

**Comment by mohrekopp** [comment]
Hi @SimonBaeumer, thank you very much. If you need any help, let me know!

**Comment by SimonBaeumer** [comment]
Hey @mohrekopp!

I just created a new pull request which is based on yours: #71.
There were some more changes you couldn't know about due to missing documentation for the 5.2 plugin system.

Would be nice if you take a short look at it. 
Again, thank you for you're great pull-request!

**Pull request closed without merging**
