### PR TITLE
Added integration for piwik/ini, guzzle and zip handling

### PR DESCRIPTION
**Pull request by tiagojsag**

### CODE REVIEW

**Comment by bcremer** [comment]
That PR broke the built, https://travis-ci.org/shopwareLabs/sw-cli-tools/builds/69141667.

Thats because guzzle6 requires PHP >= 5.5. Currently we require PHP >=5.3.2.

I would be fine bumping the requirenments to PHP 5.5.

**Comment by tiagojsag** [comment]
Yeah, we will need PHP >= 5.5, so I went ahead and bumped the requirements in composer.json

**Comment by bcremer** [comment]
The PHP 5.5 push might be a problem for our QA Team that has to use PHP 5.4 on some machines.
We might have to downgrade to guzzle5.

**Comment by bcremer** [comment]
I suppose this PR can be closed in favor of https://github.com/shopwareLabs/sw-cli-tools/pull/43/?
Feel free to reopen if not so.

**Pull request closed without merging**
