### PR TITLE
make data localizable

### PR DESCRIPTION
**Pull request by 3stadt**
Added a new optional config to make generated data localized.  
Also includes the removed fax field from PR #65

### CODE REVIEW

**Comment by mitelg** [comment]
@3stadt please update your branch and resolve the conflicts :blush: :+1:

**Comment by mitelg** [comment]
@3stadt any updates?

**Comment by mitelg** [comment]
@3stadt I'm a bit afraid to merge that :smile: 
could we talk about that?

**Comment by 3stadt** [comment]
Sure, just drop by :)

**Comment by mitelg** [comment]
@3stadt I will close this PR, ok?

**Comment by mitelg** [comment]
thanks for your contribution @3stadt :+1: :blue_heart: 
I used another PR for that, because of the rebasing stuff and so on

**Pull request closed without merging**
