### PR TITLE
Add configurable timeout to ProcessExecutor

### PR DESCRIPTION
**Pull request by tiagojsag**

### CODE REVIEW

**Comment by JanPietrzyk** [comment]
Are you sure it is necessary to even keep this? I don't see a reason for a timeout at all here.

**Comment by tiagojsag** [comment]
https://github.com/symfony/process/blob/master/Process.php#L141

By default it's 1 min, which is not enough in some cases (ES indexing, http git operations, etc).
On the other hand, setting it to a high value or null by default doesn't seem like a good idea.

**Comment by JanPietrzyk** [comment]
> On the other hand, setting it to a high value or null by default doesn't seem like a good idea.

Why not? It will still fail in case something goes wrong and the child process dies, but if the actually executed scripts do not fail, why should we bother adding a restriction that can produce seemingly random results.

**Comment by tiagojsag** [comment]
It won't produce seemingly random results, it will throw a very clear
timeout exception. On the other hand, if some child process ends up stuck
on an endless loop and there's no timeout, the end user will never know if
this is a long running process or a buggy, not exiting process. If the
process is expected to run longer than the default timeout, then it's the
dev's responsability to set a high timeout value before starting the
process, like this
https://github.com/shopware/sw-cli-tools-plugins/pull/16/files#diff-ed6e399ac60a66845ec1b3b5c924d0b5R137
(this PR is outdated btw)

**Comment by bcremer** [comment]
Someone commited the `output/` directory by accident.

**Comment by tiagojsag** [comment]
and I commited my symlinks too. But are you ok with the current solution to handle the timeout issue? @dnoegel I will squash everything into a single commit, if you dont mind

**Pull request merged**
